### PR TITLE
Not very elegant, but at least we avoid an ugly error box that has ap…

### PR DESCRIPTION
**Pull request by ceriottm**
…parently no reason and no impact. @Luthaf  you'll love it ^_^

### CODE REVIEW

**Comment by Luthaf** [comment]
This works for me =) @rosecers, you had another error message for this, right?

**Comment by ceriottm** [comment]
@rosecers if you have a different error why don't you add it in this same PR? Or perhaps we could have a list of ignored errors from JSMol?

**Comment by rosecers** [comment]
> @rosecers if you have a different error why don't you add it in this same PR? Or perhaps we could have a list of ignored errors from JSMol?

This is the primary error that I get. I get another, very similar one, but coincidentally cannot recreate it. I'll make an issue next time I come across it.

**Comment by Luthaf** [comment]
Let's update the condition next time we find one of these errors

**Pull request merged**
