### PR TITLE
Use a real orthographic camera now that 3DMol supports it fully

### PR DESCRIPTION
**Pull request by Luthaf**

### CODE REVIEW

**Comment by ceriottm** [comment]
The orthographic view works beautifully, but for some reason the azaphenacene example remains stuck in a neverending loading loop
image

IDK how it can be related, doesn't show up in the deployed website

**Comment by Luthaf** [comment]
Is this happening with a localhost version of chemiscope?

**Comment by ceriottm** [comment]
> Is this happening with a localhost version of chemiscope?

yes

**Comment by ceriottm** [comment]
actually this also happens on master, so it's unrelated.

**Comment by Luthaf** [comment]
Ok, let's merge this and figure out the issue with azaphenacenes separately

**Pull request merged**
