### PR TITLE
Move code dealing with playback to the info panel

### PR DESCRIPTION
**Pull request by Luthaf**
The only part required to live in the structure panel is the delay setting.

### CODE REVIEW

**Comment by ceriottm** [comment]
Works, but not setting the delay. When loading a file I get errors of the form 
```
Error: unable to get element with id chsp-1ae66519-3fd9-4e3e-82fb-9279ec57df06-trajectory-settings-group

Backtrace
Error: unable to get element with id chsp-1ae66519-3fd9-4e3e-82fb-9279ec57df06-trajectory-settings-group
at getByID (http://localhost:8080/chemiscope-app.min.js:225871:15)
at MoleculeViewer.__webpack_modules__../src/structure/widget.ts.MoleculeViewer.load (http://localhost:8080/chemiscope-app.min.js:225096:53)
at ViewersGrid.__webpack_modules__../src/structure/grid.ts.ViewersGrid._showInViewer (http://localhost:8080/chemiscope-app.min.js:224367:20)
at ViewersGrid.__webpack_modules__../src/structure/grid.ts.ViewersGrid.show (http://localhost:8080/chemiscope-app.min.js:224142:14)
at EnvironmentInfo.DefaultVisualizer.info.onchange (http://localhost:8080/chemiscope-app.min.js:219742:29)
at http://localhost:8080/chemiscope-app.min.js:220210:27
```

**Comment by Luthaf** [comment]
That looks related to a different part of the code =|. Do you get this error with the usual example files? Or when manually loading?

**Comment by ceriottm** [comment]
With the usual example files when running locally.  Also, changes to the
delay seems not to affect the speed of "playback"

**Review by ceriottm — APPROVED** [review]
Works well and seems to me it's simplifying the logic quite a bit. As soon as it's merged we can rebase the other PR

**Pull request merged**
